Update push.yaml

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -36,8 +36,12 @@ jobs:
           curl -X GET -H "x-api-key: ${{secrets.CARONTE_API_KEY}}" "${{secrets.CARONTE_ENDPOINT}}/v0/secgate?findingName=&findingID=HS-JAVA-134&service=horusec"
           sg_status=$(curl -X GET -H "x-api-key: ${{secrets.CARONTE_API_KEY}}" "${{secrets.CARONTE_ENDPOINT}}/v0/secgate?findingName=&findingID=HS-JAVA-134&service=horusec" | cut -d "," -f 3 | cut -d ":" -f 2)
           sg_type=$(curl -X GET -H "x-api-key: ${{secrets.CARONTE_API_KEY}}" "${{secrets.CARONTE_ENDPOINT}}/v0/secgate?findingName=&findingID=HS-JAVA-134&service=horusec" | cut -d "," -f 4 | cut -d ":" -f 2)
-          echo $sg_type
-          [ "$sg_status" = "True" ] && [ "$sg_type" = "hard" ] && exit 0
+          if [ "$sg_status" = "True" ] && [ "$sg_type" = "hard" ]; then
+            echo "Both sg_status and sg_type meet the criteria. Failing the workflow."
+            exit 1
+          else
+            echo "Conditions not met. Continuing with the workflow."
+          fi
           
 
       #  id: run_horusec
