Update push.yaml

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -38,16 +38,18 @@ jobs:
           sg_type=$(curl -X GET -H "x-api-key: ${{secrets.CARONTE_API_KEY}}" "${{secrets.CARONTE_ENDPOINT}}/v0/secgate?findingName=&findingID=HS-JAVA-134&service=horusec" | cut -d "," -f 4 | cut -d ":" -f 2)
           sg_status=$(echo "$sg_status" | tr -d '"')
           sg_type=$(echo "$sg_type" | tr -d '"')
-          echo "$sg_status"
-          echo "$sg_type"
-          if [ "$sg_status" = "True" ] && [ "$sg_type" = "hard" ]; then
-            echo "Both sg_status and sg_type meet the criteria. Failing the workflow."
-            exit 1
-          else
-            echo "Conditions not met. Continuing with the workflow."
-          fi
+          
+          json=$(curl -X GET -H "x-api-key: ${{secrets.CARONTE_API_KEY}}" "${{secrets.CARONTE_ENDPOINT}}/v0/secgate?findingName=&findingID=HS-JAVA-134&service=horusec")
 
-      #  id: run_horusec
-      #  uses: fike/horusec-action@v0.1
-      #  with:
-      #    arguments: -p="project/"
+          # Extraer los valores de "status" y "type" usando jq
+          status=$(echo "$json" | jq -r '.status')
+          type=$(echo "$json" | jq -r '.type')
+
+          echo $status
+          echo "$type"
+
+          # Verificar las condiciones
+          if [[ "$status" == "True" && "$type" == "hard" ]]; then
+              echo "Error: El valor de 'status' es 'True' y el de 'type' es 'hard'."
+              exit 1
+          fi
