Update push.yaml

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -38,16 +38,13 @@ jobs:
           sg_type=$(curl -X GET -H "x-api-key: ${{secrets.CARONTE_API_KEY}}" "${{secrets.CARONTE_ENDPOINT}}/v0/secgate?findingName=&findingID=HS-JAVA-134&service=horusec" | cut -d "," -f 4 | cut -d ":" -f 2)
           sg_status=$(echo "$sg_status" | tr -d '"')
           sg_type=$(echo "$sg_type" | tr -d '"')
-          echo ""
-          sg_status=$(echo "$sg_status" | tr -d '"')
           echo "$sg_status"
-          echo ""
           echo "$sg_type"
-          if [$sg_type = "hard"]; then
-            echo "HARD"
-          fi
-          if [$sg_type = "soft"]; then
-            echo "SOFT"
+          if [ "$sg_status" = "True" ] && [ "$sg_type" = "hard" ]; then
+            echo "Both sg_status and sg_type meet the criteria. Failing the workflow."
+            exit 1
+          else
+            echo "Conditions not met. Continuing with the workflow."
           fi
 
       #  id: run_horusec
